/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIGenerateImageModal: typeof import('./components/AIGenerateImageModal.vue')['default']
    AppAddress: typeof import('./components/AppAddress.vue')['default']
    AppCancelDialog: typeof import('./components/AppCancelDialog.vue')['default']
    AppCrudTable: typeof import('./components/app-crud-table/AppCrudTable.vue')['default']
    AppEditor: typeof import('./components/app-editor/index.vue')['default']
    AppField: typeof import('./components/AppField.vue')['default']
    AppFreeDate: typeof import('./components/app-free-date/index.vue')['default']
    AppList: typeof import('./components/AppList.vue')['default']
    AppMapDraw: typeof import('./components/AppMapDraw.vue')['default']
    AppProject: typeof import('./components/AppProject.vue')['default']
    AppTable: typeof import('./components/AppTable.vue')['default']
    AppUpload: typeof import('./components/AppUpload.vue')['default']
    CrudAuditModal: typeof import('./components/app-crud-table/parts/CrudAuditModal.vue')['default']
    CrudDetailView: typeof import('./components/app-crud-table/parts/CrudDetailView.vue')['default']
    CrudFilterBar: typeof import('./components/app-crud-table/parts/CrudFilterBar.vue')['default']
    CrudFormActions: typeof import('./components/app-crud-table/parts/CrudFormActions.vue')['default']
    CrudGrid: typeof import('./components/app-crud-table/parts/CrudGrid.vue')['default']
    CrudRowActionBar: typeof import('./components/app-crud-table/parts/CrudRowActionBar.vue')['default']
    CrudToolbar: typeof import('./components/app-crud-table/parts/CrudToolbar.vue')['default']
    Example: typeof import('./components/app-free-date/example.vue')['default']
    PersonForm: typeof import('./components/PersonForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmissionEdit: typeof import('./components/SubmissionEdit.vue')['default']
  }
}
