/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCancel: typeof import('./components/AppCancel.vue')['default']
    AppChooseLoation: typeof import('./components/AppChooseLoation.vue')['default']
    AppDatetime: typeof import('./components/AppDatetime.vue')['default']
    AppDatetimeBAK: typeof import('./components/AppDatetimeBAK.vue')['default']
    AppDetail: typeof import('./components/AppDetail.vue')['default']
    AppEditor: typeof import('./components/AppEditor/index.vue')['default']
    AppField: typeof import('./components/AppField.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppForm: typeof import('./components/AppForm.vue')['default']
    AppFormBak: typeof import('./components/AppFormBak.vue')['default']
    AppList: typeof import('./components/AppList.vue')['default']
    AppListBAK: typeof import('./components/AppListBAK.vue')['default']
    AppNested: typeof import('./components/AppNested.vue')['default']
    AppOffice: typeof import('./components/AppOffice.vue')['default']
    AppPdfViewer: typeof import('./components/AppPdfViewer.vue')['default']
    AppPrintTemplate: typeof import('./components/AppPrintTemplate/index.vue')['default']
    AppRegion: typeof import('./components/AppRegion/index.vue')['default']
    AppTable: typeof import('./components/AppTable.vue')['default']
    AppTableBAK: typeof import('./components/AppTableBAK.vue')['default']
    AppTableSelect: typeof import('./components/AppTableSelect.vue')['default']
    AppTree: typeof import('./components/AppTree.vue')['default']
    AppTreeSelect: typeof import('./components/AppTreeSelect.vue')['default']
    AppUpload: typeof import('./components/AppUpload.vue')['default']
    FormRecord: typeof import('./components/Biz/FormRecord.vue')['default']
    IndexUNIVER: typeof import('./components/AppPrintTemplate/indexUNIVER.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
